Added Dockerfile and steps in README on how to use it
fluencelabs/fRPC-Substrate pull request #15
Opened 2023-03-14 20:06 UTC by 0xThresh

I created a Dockerfile in order to run the gateway as a container and figured it could be beneficial to other developers interested in using the fRPC Gateway. The benefits of the container approach are:
- Easier portability to run gateway in a shared location for use by teams (such as on a cloud server/ container service like Amazon ECS) 
- Fewer manual steps to run gateway
- Less package clutter on your local machine 

I added documentation to the README that should be sufficient to get the container running, assuming the user already has Docker installed locally. There is an assumption that the config file with providers is edited prior to the Dockerfile being built since that file is copied directly into the container's filesystem, which is why the steps to use the container come after the config file steps in the README. The `curl` test provided in the README should be sufficient to test the gateway running in the container without any extra steps since the documented `docker run` command exposes port 3000. 

Please let me know if you have any questions or run into any issues while testing. Thank you!

2023-03-14 20:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/fluencelabs/fRPC-Substrate?pullRequest=15) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/fluencelabs/fRPC-Substrate?pullRequest=15) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/fluencelabs/fRPC-Substrate?pullRequest=15) it.</sub>

2023-03-18 22:39 UTC, boneyard93501 commented
thanks for the submission.  couple minor changes would be good.

2023-03-19 00:12 UTC, 0xThresh commented
Hey @boneyard93501, happy to make changes but didn't see a review requested.

2023-03-24 18:27 UTC, boneyard93501 requested changes

2023-05-06 00:54 UTC, boneyard93501 commented
going to close for now. feel free to re-open when you're ready.

2023-05-06 00:54 UTC, closed without merging